### ISSUE TITLE
BUG REPORT: report_parser does not process pathnames with spaces

### ISSUE THREAD

**Issue by joshwilding4444** [rocky-linux/testing#65]
---

When attempting to parse a file whose pathname contains a space, the parser will split the pathname into multiple parts, failing to process the file correctly.

---

1. Pass a filename containing spaces using a utility like `find`:
    - for example, the following script processes all filenames ending in `.xsos.out`:
```
#!/bin/bash

for f in $(find ./testing/test-reports -name "*.xsos.out" )
do
    echo "attempting to process $f:"
    python3 ./testing/report_parser/report_parser.py "$f" "$f.yaml"
    echo "processed $f"
done
```

---
Expected behavior is to parse the correct file normally. 

---

Error received when using the above script:
```
Traceback (most recent call last):
  File "/home/josh/Documents/work/rocky-linux/./testing/report_parser/report_parser.py", line 150, in <module>
    main()
  File "/home/josh/Documents/work/rocky-linux/./testing/report_parser/report_parser.py", line 147, in main
    read_entire_file(sys.argv[1], sys.argv[2])
  File "/home/josh/Documents/work/rocky-linux/./testing/report_parser/report_parser.py", line 126, in read_entire_file
    target_file = open(input_filename)
FileNotFoundError: [Errno 2] No such file or directory: './testing/test-reports/hardware/raspberry-pi/rpi'
processed ./testing/test-reports/hardware/raspberry-pi/rpi
attempting to process 3b+/7b5ccd10-2bcb-4166-bba9-336858be12e6.xsos.out:
Traceback (most recent call last):
  File "/home/josh/Documents/work/rocky-linux/./testing/report_parser/report_parser.py", line 150, in <module>
    main()
  File "/home/josh/Documents/work/rocky-linux/./testing/report_parser/report_parser.py", line 147, in main
    read_entire_file(sys.argv[1], sys.argv[2])
  File "/home/josh/Documents/work/rocky-linux/./testing/report_parser/report_parser.py", line 126, in read_entire_file
    target_file = open(input_filename)
FileNotFoundError: [Errno 2] No such file or directory: '3b+/7b5ccd10-2bcb-4166-bba9-336858be12e6.xsos.out'
```

---

**System / Environment (please complete the following information):**

- OS: Ubuntu
- OS Version: 21.04
- Testing Repository
  - Branch: main
  - Hash: ca74758f4749ff9b45fbf1a0ec46b247f011aacc
  - Script / Tool: report_parser.py

---
Adding a '\\' to the pathname will allow the script to parse the file correctly:
```
~$ python3 ./report_parser/report_parser.py ./test-reports/hardware/raspberry-pi/rpi\ 3b+/7b5ccd10-2bcb-4166-bba9-336858be12e6.xsos.out ./test_without_quotes.yaml
```

**Comment by sibuthomasmathew** [comment]
Hi @joshwilding4444,

Rather than this being an issue with the python parser script, I believe it has more to do with how the shell `for` loop interprets field separators. The variable is `$IFS` and it is set to white space characters by default.

Please try the below script and let me know if it helps:
```
#!/bin/bash

IFS=$'\n'
for f in $(find ./testing/test-reports -name "*.xsos.out" )
do
    echo "attempting to process $f:"
    python3 ./testing/report_parser/report_parser.py "$f" "$f.yaml"
    echo "processed $f"
done
```

Alternatively, a one liner would be:
```
find ./testing/test-reports -type f -name "*.xsos.out"  | while read f; do python3 ./testing/report_parser/report_parser.py "$f" "$f.yaml"; done
```

Please let me know if it helps or whether I misunderstood the issue.

**Comment by joshwilding4444** [comment]
Sorry for the late reply, but setting the IFS variable resolved the issue. Thank you.
