### ISSUE TITLE
Should Color be on or off in output?

### ISSUE THREAD

**Issue by preachermanx** [rocky-linux/testing#8]
I personally prefer color but I want to know what we should use by default.

**Comment by StackKorora** [comment]
My recommendation is to have it off. I've added it in the the pull request #3 . When I tried to capture the colors it was a bit of a formatting mess. I think having the colors off would make it cleaner for us to parse and scrape information.

**Comment by tcooper** [comment]
For the purposes we are proposing it's probably better to keep color off. I've been copy/pasting the output from remote systems to my repo so I didn't really think about it but automated parsing with codes will be much harder.

**Comment by alexhaydock** [comment]
I definitely agree that colour should be turned off in the output. I just generated some reports using the (current) README instructions and in a regular text editor they're unreadable without disabling colour.

**Comment by tcooper** [comment]
Removal of color output is included in #3.
